import { PERMISSIONS } from './permissions';

export const ROLE_PERMISSIONS = {
  admin: [
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.PROJECT_READ,
  ],
  editor: [
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_READ,
  ],
  viewer: [
    PERMISSIONS.PROJECT_READ,
  ],
} as const;
